apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arm-protocol-traces
  labels:
    app: arm-protocol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
